[package]
name = "fabric"
path = ""

[dependencies]
"net.fabricmc.fabric-loader" = "0.19.3"
"net.fabricmc.fabric-log4j-util" = "1.0.2"
"net.fabricmc.dev-launch-injector" = "0.2.1+build.8"
"net.fabricmc.sponge-mixin" = "0.17.3+mixin.0.8.7"
"io.github.llamalad7.mixinextras-fabric" = "0.5.4"

[versions."0.19.3"]
runtime = []
sources = []
