[package]
name = "template-mod"
path = "com.example"
ver = "1.0.0"

[extra]
display_name = "Template Mod"
this_can_be_anything = "true"

[dependencies]
fabric = "0.19.3"
fabric-api = "0.155.2+26.2"
minecraft = "26.2"
minecraft-client = "26.2"
test = { version = "1.0.0", embedded = true, location = "test" }

[version]
runtime = ["template-mod.jar"]
sources = ["template-mod-sources.jar"]
